# This workflow will do a clean install of node dependencies and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: javascript-representer / main

on:
  push:
    branches: [main]

jobs:
  precheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js LTS (16.x)
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install project dependencies
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: Lint code
        run: yarn lint

  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install project dependencies and run tests
        run: yarn install --frozen-lockfile
