# This workflow will do a clean install of node dependencies and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: javascript-representer / pr

on: pull_request

jobs:
  precheck:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout PR
        uses: actions/checkout@v2

      - name: Use Node.js LTS (16.x)
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install project dependencies
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: Lint code
        run: yarn lint

  unit_tests:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout PR
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install project dependencies and run tests
        run: yarn install --frozen-lockfile

  smoke_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4c0219f9ac95b02789c1075625400b2acbff50b1
        with:
          install: true

      - name: Build Docker image and store in cache
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
        with:
          context: .
          push: false
          load: true
          tags: exercism/javascript-representer
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Tests in Docker
        run: bin/run-tests-in-docker.sh
